#![doc = "Peripheral access API for MYM0CHIP microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 2;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn TIMER0_IRQn();
    fn TIMER1_IRQn();
    fn MCPWM0_IRQn();
    fn MCPWM1_IRQn();
    fn I2C_IRQn();
    fn SPI_IRQn();
    fn GPIO_IRQn();
    fn HALL_IRQn();
    fn UART_IRQn();
    fn CMP_IRQn();
    fn ADC_IRQn();
    fn DMA_IRQn();
    fn WAKE_IRQn();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 13] = [
    Vector {
        _handler: TIMER0_IRQn,
    },
    Vector {
        _handler: TIMER1_IRQn,
    },
    Vector {
        _handler: MCPWM0_IRQn,
    },
    Vector {
        _handler: MCPWM1_IRQn,
    },
    Vector { _handler: I2C_IRQn },
    Vector { _handler: SPI_IRQn },
    Vector {
        _handler: GPIO_IRQn,
    },
    Vector {
        _handler: HALL_IRQn,
    },
    Vector {
        _handler: UART_IRQn,
    },
    Vector { _handler: CMP_IRQn },
    Vector { _handler: ADC_IRQn },
    Vector { _handler: DMA_IRQn },
    Vector {
        _handler: WAKE_IRQn,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Timer 0 Interrupt"]
    TIMER0_IRQn = 0,
    #[doc = "1 - Timer 1 Interrupt"]
    TIMER1_IRQn = 1,
    #[doc = "2 - MCPWM Interrupt 0"]
    MCPWM0_IRQn = 2,
    #[doc = "3 - MCPWM Interrupt 1"]
    MCPWM1_IRQn = 3,
    #[doc = "4 - I2C Interrupt"]
    I2C_IRQn = 4,
    #[doc = "5 - SPI Interrupt"]
    SPI_IRQn = 5,
    #[doc = "6 - GPIO Interrupt"]
    GPIO_IRQn = 6,
    #[doc = "7 - Hall Sensor Interrupt"]
    HALL_IRQn = 7,
    #[doc = "8 - UART Interrupt"]
    UART_IRQn = 8,
    #[doc = "9 - Comparator Interrupt"]
    CMP_IRQn = 9,
    #[doc = "10 - ADC Interrupt"]
    ADC_IRQn = 10,
    #[doc = "11 - DMA Interrupt"]
    DMA_IRQn = 11,
    #[doc = "12 - Wake Interrupt"]
    WAKE_IRQn = 12,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Miscellaneous System Control"]
pub type Misc = crate::Periph<misc::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Misc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Misc").finish()
    }
}
#[doc = "Miscellaneous System Control"]
pub mod misc;
#[doc = "Flash Control"]
pub type FlashCtrl = crate::Periph<flash_ctrl::RegisterBlock, 0x0001_0000>;
impl core::fmt::Debug for FlashCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashCtrl").finish()
    }
}
#[doc = "Flash Control"]
pub mod flash_ctrl;
#[doc = "Serial Peripheral Interface"]
pub type Spi = crate::Periph<spi::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Spi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi").finish()
    }
}
#[doc = "Serial Peripheral Interface"]
pub mod spi;
#[doc = "I2C Interface"]
pub type I2c = crate::Periph<i2c::RegisterBlock, 0x4001_0100>;
impl core::fmt::Debug for I2c {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c").finish()
    }
}
#[doc = "I2C Interface"]
pub mod i2c;
#[doc = "Comparator"]
pub type Cmp = crate::Periph<cmp::RegisterBlock, 0x4001_0200>;
impl core::fmt::Debug for Cmp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp").finish()
    }
}
#[doc = "Comparator"]
pub mod cmp;
#[doc = "Hall Sensor Interface"]
pub type Hall = crate::Periph<hall::RegisterBlock, 0x4001_0300>;
impl core::fmt::Debug for Hall {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hall").finish()
    }
}
#[doc = "Hall Sensor Interface"]
pub mod hall;
#[doc = "Analog to Digital Converter"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "Analog to Digital Converter"]
pub mod adc;
#[doc = "Timer 0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4001_0500>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer 0"]
pub mod timer0;
#[doc = "Timer 1"]
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0x4001_0600>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "Timer 1"]
pub use self::timer0 as timer1;
#[doc = "Motor Control PWM"]
pub type Mcpwm = crate::Periph<mcpwm::RegisterBlock, 0x4001_0700>;
impl core::fmt::Debug for Mcpwm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mcpwm").finish()
    }
}
#[doc = "Motor Control PWM"]
pub mod mcpwm;
#[doc = "General Purpose I/O Port 0"]
pub type Gpio0 = crate::Periph<gpio0::RegisterBlock, 0x4001_0800>;
impl core::fmt::Debug for Gpio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0").finish()
    }
}
#[doc = "General Purpose I/O Port 0"]
pub mod gpio0;
#[doc = "General Purpose I/O Port 1"]
pub type Gpio1 = crate::Periph<gpio0::RegisterBlock, 0x4001_0840>;
impl core::fmt::Debug for Gpio1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio1").finish()
    }
}
#[doc = "General Purpose I/O Port 1"]
pub use self::gpio0 as gpio1;
#[doc = "External Interrupt Controller"]
pub type Exti = crate::Periph<exti::RegisterBlock, 0x4001_0880>;
impl core::fmt::Debug for Exti {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Exti").finish()
    }
}
#[doc = "External Interrupt Controller"]
pub mod exti;
#[doc = "UART 0"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4001_0900>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "UART 0"]
pub mod uart0;
#[doc = "Direct Memory Access"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4001_0a00>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "Direct Memory Access"]
pub mod dma;
#[doc = "DSP Coprocessor"]
pub type Dsp = crate::Periph<dsp::RegisterBlock, 0x4001_0b00>;
impl core::fmt::Debug for Dsp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dsp").finish()
    }
}
#[doc = "DSP Coprocessor"]
pub mod dsp;
#[doc = "Always On Domain"]
pub type Aon = crate::Periph<aon::RegisterBlock, 0x4001_0c00>;
impl core::fmt::Debug for Aon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aon").finish()
    }
}
#[doc = "Always On Domain"]
pub mod aon;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "MISC"]
    pub misc: Misc,
    #[doc = "FLASH_CTRL"]
    pub flash_ctrl: FlashCtrl,
    #[doc = "SPI"]
    pub spi: Spi,
    #[doc = "I2C"]
    pub i2c: I2c,
    #[doc = "CMP"]
    pub cmp: Cmp,
    #[doc = "HALL"]
    pub hall: Hall,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "MCPWM"]
    pub mcpwm: Mcpwm,
    #[doc = "GPIO0"]
    pub gpio0: Gpio0,
    #[doc = "GPIO1"]
    pub gpio1: Gpio1,
    #[doc = "EXTI"]
    pub exti: Exti,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "DSP"]
    pub dsp: Dsp,
    #[doc = "AON"]
    pub aon: Aon,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            misc: unsafe { Misc::steal() },
            flash_ctrl: unsafe { FlashCtrl::steal() },
            spi: unsafe { Spi::steal() },
            i2c: unsafe { I2c::steal() },
            cmp: unsafe { Cmp::steal() },
            hall: unsafe { Hall::steal() },
            adc: unsafe { Adc::steal() },
            timer0: unsafe { Timer0::steal() },
            timer1: unsafe { Timer1::steal() },
            mcpwm: unsafe { Mcpwm::steal() },
            gpio0: unsafe { Gpio0::steal() },
            gpio1: unsafe { Gpio1::steal() },
            exti: unsafe { Exti::steal() },
            uart0: unsafe { Uart0::steal() },
            dma: unsafe { Dma::steal() },
            dsp: unsafe { Dsp::steal() },
            aon: unsafe { Aon::steal() },
        }
    }
}
